import "@/app/globals.css"
import NextTopLoader from 'nextjs-toploader';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <NextTopLoader 
        showSpinner={false}
        color="#4646d7"
        />
        {children}
      </body>
    </html>
  )
}
